"""initial schema - 7 tables

Revision ID: fe387ea30898
Revises: 
Create Date: 2026-03-02 23:45:36.006195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe387ea30898'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_key', sa.String(length=50), nullable=True),
    sa.Column('listing_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('address_normalized', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('lot_size_acres', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('property_sub_type', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('original_list_price', sa.Float(), nullable=True),
    sa.Column('previous_list_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('list_price_low', sa.Float(), nullable=True),
    sa.Column('standard_status', sa.String(length=50), nullable=True),
    sa.Column('mls_status', sa.String(length=50), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('cumulative_dom', sa.Integer(), nullable=True),
    sa.Column('listing_contract_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('on_market_date', sa.Date(), nullable=True),
    sa.Column('off_market_date', sa.Date(), nullable=True),
    sa.Column('pending_timestamp', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_date', sa.Date(), nullable=True),
    sa.Column('cancellation_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('price_change_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status_change_timestamp', sa.DateTime(), nullable=True),
    sa.Column('modification_timestamp', sa.DateTime(), nullable=True),
    sa.Column('original_entry_timestamp', sa.DateTime(), nullable=True),
    sa.Column('list_agent_key', sa.String(length=50), nullable=True),
    sa.Column('list_agent_mls_id', sa.String(length=50), nullable=True),
    sa.Column('list_agent_full_name', sa.String(length=200), nullable=True),
    sa.Column('list_office_mls_id', sa.String(length=50), nullable=True),
    sa.Column('list_office_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_agent_key', sa.String(length=50), nullable=True),
    sa.Column('foreclosed_reo', sa.Boolean(), nullable=False),
    sa.Column('potential_short_sale', sa.Boolean(), nullable=False),
    sa.Column('gulf_access', sa.Boolean(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('owner_mailing_address', sa.String(length=300), nullable=True),
    sa.Column('is_absentee', sa.Boolean(), nullable=False),
    sa.Column('is_corporate', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_listing_id'), 'properties', ['listing_id'], unique=False)
    op.create_index(op.f('ix_properties_listing_key'), 'properties', ['listing_key'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('last_touch_at', sa.DateTime(), nullable=True),
    sa.Column('next_touch_date', sa.DateTime(), nullable=True),
    sa.Column('contact_attempts', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=100), nullable=True),
    sa.Column('crm_synced_at', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_property_id'), 'leads', ['property_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_property_id'), 'price_history', ['property_id'], unique=False)
    op.create_table('outreach_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('outreach_type', sa.String(length=30), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_events_lead_id'), 'outreach_events', ['lead_id'], unique=False)
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.String(length=200), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_history_lead_id'), 'score_history', ['lead_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('base_points', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('decay_type', sa.String(length=20), nullable=False),
    sa.Column('half_life_days', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_lead_id'), 'signals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_signals_property_id'), 'signals', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_property_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_lead_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_score_history_lead_id'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_index(op.f('ix_outreach_events_lead_id'), table_name='outreach_events')
    op.drop_table('outreach_events')
    op.drop_index(op.f('ix_price_history_property_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_leads_property_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_properties_listing_key'), table_name='properties')
    op.drop_index(op.f('ix_properties_listing_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
